print(" ")
print(" ")
print("J J J J J")
print("    J    ")
print("    J    ")
print("    J    ")
print("J   J    ")
print("J   J    ")
print("  J J    ")
print(" ")
print(" ")
print("  C C C  ")
print("C       C")
print("C        ")
print("C        ")
print("C        ")
print("C       C")
print("  C C C  ")
